### PR TITLE
Switch to GitHub actions (updated)

### LINKED ISSUE #27: Windows binary
Hi,

I found your repo yesterday. Great stuff.

How about automatic windows binaries during every release. Would love to help out with a msi installer. Did this already in one of my projects.

Would love to do that if you put an hacktoberfest label on this issue ;)

### PR DESCRIPTION
**Pull request by dolsem**
I took another stab at it, building on top of https://github.com/wchang22/LuminS/pull/32. I ended up replacing kcov with tarpaulin, which is a Cargo code coverage tool. This is the cleanest/simplest approach I could find. You might be aware that the current code coverage process with kcov has been broken for a while anyway (see line 786 here - https://travis-ci.org/github/wchang22/LuminS/jobs/703374950#L786).

Fixes https://github.com/wchang22/LuminS/issues/27

### CODE REVIEW

**Comment by dolsem** [comment]
You can see a successful run here - https://github.com/dolsem/LuminS/actions/runs/2181224928

**Comment by dolsem** [comment]
@wchang22 pinging to see if I could get any update

**Comment by wchang22** [comment]
@dolsem Thanks for this (and for pinging me)! Lgtm, I'll merge it

**Comment by aminya** [comment]
Thanks for completing the work

**Pull request merged**
