### PR TITLE
Add Github actions with support for Linux, Windows, Mac

### LINKED ISSUE #27: Windows binary
Hi,

I found your repo yesterday. Great stuff.

How about automatic windows binaries during every release. Would love to help out with a msi installer. Did this already in one of my projects.

Would love to do that if you put an hacktoberfest label on this issue ;)

### PR DESCRIPTION
**Pull request by aminya**
Fixes #27

An example of a successful run:
https://github.com/aminya/LuminS/actions/runs/1299883453
image

### CODE REVIEW

**Comment by aminya** [comment]
I noticed that you use kcov to collect coverage for the tests. If desired we can do the same in Github Actions, and then remove the Travis file.

**Comment by ErisMik** [comment]
This looks great and I'm happy to merge it in, but it looks like the travis check is broken and blocking the merge. I'll have to get some additional privileges from the repo owner before we continue.

**Comment by wchang22** [comment]
@aminya Thanks for this. Travis should be fixed, so if you can add kcov, we can merge this and then remove travis.

**Comment by wchang22** [comment]
Fixed by #37

**Pull request closed without merging**
